#ifndef IG_SHADER_BINDINGS_H
#define IG_SHADER_BINDINGS_H

#define SH_BIND_GLOBAL_CONSTANTS			0
#define SH_BIND_TRANSFORM					1

// Forward shading
#define SH_BIND_FWDSH_ALBEDO_TEX			2
#define SH_BIND_FWDSH_SHADOWMAP_TEX			3
#define SH_BIND_FWDSH_LIGHTPROJ_TEX			4
#define SH_BIND_FWDSH_LIGHTMATRIX			5

// Pathtracer
#define SH_BIND_PATHTRACER_NOISE_TEX		2


#endif // IG_SHADER_BINDINGS_H